# Servers
#
servers:
    -
        host: "%parameters.server_default_host%"
        port: "%parameters.server_default_port%"
        routes: "%configuration_directory_path%/routes.yml"


# http routeur configuration
http_router:
    debug: true
